### ISSUE TITLE
KickRedirect not working

### ISSUE THREAD

**Issue by Pantera07** [4drian3d/KickRedirect#1]
KickRedirect not working

KickRedirect 1.2.1
Velocity #138

**Comment by Pantera07** [comment]
@4drian3d 
have you tried it?

**Comment by 4drian3d** [comment]
Could you try using the new version? https://github.com/4drian3d/KickRedirect/releases/tag/2.0.0

**Comment by Pantera07** [comment]
> Could you try using the new version? https://github.com/4drian3d/KickRedirect/releases/tag/2.0.0

```
[00:49:04 INFO]: Loading plugins...
[00:49:04 INFO]: Loaded plugin kickredirect 2.0.0 by 4drian3d
[00:49:04 INFO]: Loaded 1 plugins
[00:49:04 INFO]: [KickRedirect] Starting plugin...
[00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/spongepowered/configurate-hocon/4.1.2/configurate-hocon-4.1.2.jar
[00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
[00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/ow2/asm/asm/9.2/asm-9.2.jar
[00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/me/lucko/jar-relocator/1.5/jar-relocator-1.5.jar
[00:49:05 INFO] [kickredirect]: Relocations applied to libs\org\spongepowered\configurate-hocon\4.1.2\configurate-hocon-4.1.2.jar
[00:49:06 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/spongepowered/configurate-core/4.1.2/configurate-core-4.1.2.jar
[00:49:06 INFO] [kickredirect]: Relocations applied to libs\org\spongepowered\configurate-core\4.1.2\configurate-core-4.1.2.jar
[00:49:06 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/io/leangen/geantyref/geantyref/1.3.13/geantyref-1.3.13.jar
[00:49:06 INFO] [kickredirect]: Relocations applied to libs\io\leangen\geantyref\geantyref\1.3.13\geantyref-1.3.13.jar
[00:49:07 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/3.0.6/caffeine-3.0.6.jar
[00:49:07 INFO] [kickredirect]: Relocations applied to libs\com\github\ben-manes\caffeine\caffeine\3.0.6\caffeine-3.0.6.jar
[00:49:07 ERROR]: Couldn't pass ProxyInitializeEvent to kickredirect
java.lang.NoClassDefFoundError: io/leangen/geantyref/TypeToken
        at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.ScalarSerializer.<init>(ScalarSerializer.java:71) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.BooleanSerializer.<init>(BooleanSerializer.java:39) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.Scalars.<clinit>(Scalars.java:46) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.TypeSerializerCollection.<clinit>(TypeSerializerCollection.java:50) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.ConfigurationOptions$Lazy.<clinit>(ConfigurationOptions.java:56) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.ConfigurationOptions.defaults(ConfigurationOptions.java:73) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.loader.AbstractConfigurationLoader$Builder.<init>(AbstractConfigurationLoader.java:269) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.hocon.HoconConfigurationLoader$Builder.<init>(HoconConfigurationLoader.java:96) ~[?:?]
        at me.dreamerzero.kickredirect.libs.sponge.configurate.hocon.HoconConfigurationLoader.builder(HoconConfigurationLoader.java:85) ~[?:?]
        at me.dreamerzero.kickredirect.configuration.Configuration.loadMainConfig(Configuration.java:16) ~[?:?]
        at me.dreamerzero.kickredirect.KickRedirect.loadConfig(KickRedirect.java:156) ~[?:?]
        at me.dreamerzero.kickredirect.KickRedirect.initialize(KickRedirect.java:169) ~[?:?]
        at me.dreamerzero.kickredirect.KickRedirect.onProxyInitialization(KickRedirect.java:77) ~[?:?]
        at me.dreamerzero.kickredirect.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: io.leangen.geantyref.TypeToken
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:85) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:62) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 20 more
```
An error occurred

KickRedirect 2.0.0
Velocity #140

**Comment by 4drian3d** [comment]
> > Could you try using the new version? https://github.com/4drian3d/KickRedirect/releases/tag/2.0.0
> 
> ```
> [00:49:04 INFO]: Loading plugins...
> [00:49:04 INFO]: Loaded plugin kickredirect 2.0.0 by 4drian3d
> [00:49:04 INFO]: Loaded 1 plugins
> [00:49:04 INFO]: [KickRedirect] Starting plugin...
> [00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/spongepowered/configurate-hocon/4.1.2/configurate-hocon-4.1.2.jar
> [00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
> [00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/ow2/asm/asm/9.2/asm-9.2.jar
> [00:49:05 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/me/lucko/jar-relocator/1.5/jar-relocator-1.5.jar
> [00:49:05 INFO] [kickredirect]: Relocations applied to libs\org\spongepowered\configurate-hocon\4.1.2\configurate-hocon-4.1.2.jar
> [00:49:06 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/org/spongepowered/configurate-core/4.1.2/configurate-core-4.1.2.jar
> [00:49:06 INFO] [kickredirect]: Relocations applied to libs\org\spongepowered\configurate-core\4.1.2\configurate-core-4.1.2.jar
> [00:49:06 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/io/leangen/geantyref/geantyref/1.3.13/geantyref-1.3.13.jar
> [00:49:06 INFO] [kickredirect]: Relocations applied to libs\io\leangen\geantyref\geantyref\1.3.13\geantyref-1.3.13.jar
> [00:49:07 INFO] [kickredirect]: Downloaded library https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/3.0.6/caffeine-3.0.6.jar
> [00:49:07 INFO] [kickredirect]: Relocations applied to libs\com\github\ben-manes\caffeine\caffeine\3.0.6\caffeine-3.0.6.jar
> [00:49:07 ERROR]: Couldn't pass ProxyInitializeEvent to kickredirect
> java.lang.NoClassDefFoundError: io/leangen/geantyref/TypeToken
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.ScalarSerializer.<init>(ScalarSerializer.java:71) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.BooleanSerializer.<init>(BooleanSerializer.java:39) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.Scalars.<clinit>(Scalars.java:46) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.serialize.TypeSerializerCollection.<clinit>(TypeSerializerCollection.java:50) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.ConfigurationOptions$Lazy.<clinit>(ConfigurationOptions.java:56) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.ConfigurationOptions.defaults(ConfigurationOptions.java:73) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.loader.AbstractConfigurationLoader$Builder.<init>(AbstractConfigurationLoader.java:269) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.hocon.HoconConfigurationLoader$Builder.<init>(HoconConfigurationLoader.java:96) ~[?:?]
>         at me.dreamerzero.kickredirect.libs.sponge.configurate.hocon.HoconConfigurationLoader.builder(HoconConfigurationLoader.java:85) ~[?:?]
>         at me.dreamerzero.kickredirect.configuration.Configuration.loadMainConfig(Configuration.java:16) ~[?:?]
>         at me.dreamerzero.kickredirect.KickRedirect.loadConfig(KickRedirect.java:156) ~[?:?]
>         at me.dreamerzero.kickredirect.KickRedirect.initialize(KickRedirect.java:169) ~[?:?]
>         at me.dreamerzero.kickredirect.KickRedirect.onProxyInitialization(KickRedirect.java:77) ~[?:?]
>         at me.dreamerzero.kickredirect.Lmbda$1.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.ClassNotFoundException: io.leangen.geantyref.TypeToken
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:85) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:62) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
>         ... 20 more
> ```
> 
> An error occurred
> 
> KickRedirect 2.0.0 Velocity #140

Fixed https://github.com/4drian3d/KickRedirect/releases/tag/2.0.1

> For this change to take effect you must delete the kickredirect/libs folder to allow it to regenerate

**Comment by Pantera07** [comment]
> > In what way does it not work? Could you provide more information?
> 
> When a player is kicked, that player does not go to the `servers-to-redirect` server.

@4drian3d 
Still have this bug.
When a player is kicked, they move to the server set in `velocity.toml` - `try`.

**Comment by 4drian3d** [comment]
Maybe another plugin is controlling the logic in the kick, activate debug in the configuration, it should tell you what the problem is

**Comment by Pantera07** [comment]
@4drian3d 
> Maybe another plugin is controlling the logic in the kick, activate debug in the configuration, it should tell you what the problem is

I uninstalled all other Velocity plugins. But KickRedirect is not working.

```
[14:53:56] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[14:54:47] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:5709) has disconnected
[14:54:47] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[14:54:49] [Netty NIO Worker #4/INFO]: [connected player] Mad_Daniel (/127.0.0.1:5789) has connected
[14:54:49] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has connected
[14:55:27] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> survival has connected
[14:55:27] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[14:55:42] [Netty NIO Worker #4/INFO]: [connected player] Mad_Daniel (/127.0.0.1:5789): kicked from server survival: multiplayer.disconnect.kicked
[14:55:42] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[14:55:42] [Velocity Async Event Executor - #4/INFO]: Player: Mad_Daniel, Server: survival, Kicked in Server Connect: false, Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[14:55:42] [Velocity Async Event Executor - #4/INFO]: Player: Mad_Daniel, Server: survival, Kicked in Server Connect: false, Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[14:55:42] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has connected
[14:55:51] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> survival has connected
[14:55:51] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[14:56:00] [Netty NIO Worker #4/INFO]: [connected player] Mad_Daniel (/127.0.0.1:5789): kicked from server survival: test
[14:56:00] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[14:56:00] [Velocity Async Event Executor - #6/INFO]: Player: Mad_Daniel, Server: survival, Kicked in Server Connect: false, Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[14:56:00] [Velocity Async Event Executor - #6/INFO]: Player: Mad_Daniel, Server: survival, Kicked in Server Connect: false, Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[14:56:00] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has connected
[14:56:05] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> survival has connected
[14:56:05] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[14:56:31] [Netty NIO Worker #4/INFO]: [connected player] Mad_Daniel (/127.0.0.1:5789): kicked from server survival: kicked from server
[14:56:31] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[14:56:31] [Velocity Async Event Executor - #0/INFO]: Player: Mad_Daniel, Server: survival, Kicked in Server Connect: false, Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[14:56:31] [Velocity Async Event Executor - #0/INFO]: Player: Mad_Daniel, Server: survival, Kicked in Server Connect: false, Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[14:56:31] [Netty NIO Worker #4/INFO]: [server connection] Mad_Daniel -> lobby has connected
```
`velocity.toml`
![화면 캡처 2022-06-15 145906](https://user-images.githubusercontent.com/89838384/173753424-c4841f4b-9b47-4e99-a2dd-9c881d3afc8c.png)

`config.conf`
![1](https://user-images.githubusercontent.com/89838384/173753440-a47276a8-ece6-464c-a755-b7e9afb1bfd1.png)

**Comment by 4drian3d** [comment]
You can try again with https://github.com/4drian3d/KickRedirect/actions/runs/2503750921 `KickRedirect-2.0.1-all.jar`

**Comment by 4drian3d** [comment]
I have put even more tests and fixed some bugs, everything seems to work fine, could you try again with the new release? https://github.com/4drian3d/KickRedirect/releases/tag/2.0.2

**Comment by Pantera07** [comment]
`Version 2.0.2` and `Build #25` still not working.

```
[13:38:01] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:2577) has connected
[13:38:01] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[13:38:06] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
[13:38:06] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[13:38:16] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:2577): kicked from server survival: multiplayer.disconnect.kicked
[13:38:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[13:38:16] [Velocity Async Event Executor - #2/INFO]: Player: Mad_Daniel
 Server: NONE
 Kicked in Server Connect: false
 Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[13:38:16] [Velocity Async Event Executor - #2/INFO]: Player: Mad_Daniel
 Server: lobby
 Kicked in Server Connect: false
 Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[13:38:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[13:38:21] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
[13:38:21] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[13:38:32] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:2577): kicked from server survival: test
[13:38:32] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[13:38:32] [Velocity Async Event Executor - #4/INFO]: Player: Mad_Daniel
 Server: NONE
 Kicked in Server Connect: false
 Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[13:38:32] [Velocity Async Event Executor - #4/INFO]: Player: Mad_Daniel
 Server: lobby
 Kicked in Server Connect: false
 Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[13:38:32] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[13:38:38] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
[13:38:38] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[13:38:51] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:2577): kicked from server survival: kicked from server
[13:38:51] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[13:38:51] [Velocity Async Event Executor - #6/INFO]: Player: Mad_Daniel
 Server: NONE
 Kicked in Server Connect: false
 Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[13:38:51] [Velocity Async Event Executor - #6/INFO]: Player: Mad_Daniel
 Server: lobby
 Kicked in Server Connect: false
 Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
[13:38:51] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
```

**Comment by 4drian3d** [comment]
Could you try the latest build? It should say a better debug message (you have to restart the config or the specific message option to re-generate it)

**Comment by Pantera07** [comment]
@4drian3d 
> Could you try the latest build? It should say a better debug message (you have to restart the config or the specific message option to re-generate it)

```
[22:18:27] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-1a1391a5-b155)...
[22:18:27] [main/INFO]: Loading localizations...
[22:18:27] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
[22:18:27] [main/INFO]: Loading plugins...
[22:18:28] [main/INFO]: Loaded plugin kickredirect 2.0.2 by 4drian3d
[22:18:28] [main/INFO]: Loaded 1 plugins
[22:18:28] [Velocity Async Event Executor - #0/INFO]: [KickRedirect] Starting plugin...
[22:18:28] [Velocity Async Event Executor - #0/INFO]: [KickRedirect] Fully started plugin in 176ms
[22:18:28] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[22:18:28] [main/INFO]: Done (1.33s)!
[22:19:47] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283) has connected
[22:19:47] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[22:20:12] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
[22:20:13] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[22:20:38] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283): kicked from server survival: multiplayer.disconnect.kicked
[22:20:38] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[22:20:38] [Velocity Async Event Executor - #2/INFO]: ----- INITIAL DEBUG ----- 
 Player: Mad_Daniel
 Server: NONE
 Kick Reason: multiplayer.disconnect.kicked
 Kicked in Server Connect: false
 Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
 Step: NOT_ALLOWED
[22:20:38] [Velocity Async Event Executor - #2/INFO]: ----- FINAL DEBUG -----
 Player: Mad_Daniel
 Server: lobby
 Kick Reason: multiplayer.disconnect.kicked
 Kicked in Server Connect: false
 Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
 Step: NOT_ALLOWED
[22:20:38] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[22:20:49] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
[22:20:49] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[22:21:10] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283): kicked from server survival: test
[22:21:10] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[22:21:10] [Velocity Async Event Executor - #4/INFO]: ----- INITIAL DEBUG ----- 
 Player: Mad_Daniel
 Server: NONE
 Kick Reason: test
 Kicked in Server Connect: false
 Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
 Step: NOT_ALLOWED
[22:21:10] [Velocity Async Event Executor - #4/INFO]: ----- FINAL DEBUG -----
 Player: Mad_Daniel
 Server: lobby
 Kick Reason: test
 Kicked in Server Connect: false
 Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
 Step: NOT_ALLOWED
[22:21:10] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[22:21:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
[22:21:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
[22:21:39] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283): kicked from server survival: kicked from server
[22:21:39] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
[22:21:39] [Velocity Async Event Executor - #6/INFO]: ----- INITIAL DEBUG ----- 
 Player: Mad_Daniel
 Server: NONE
 Kick Reason: kicked from server
 Kicked in Server Connect: false
 Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
 Step: NOT_ALLOWED
[22:21:39] [Velocity Async Event Executor - #6/INFO]: ----- FINAL DEBUG -----
 Player: Mad_Daniel
 Server: lobby
 Kick Reason: kicked from server
 Kicked in Server Connect: false
 Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
 Step: NOT_ALLOWED
[22:21:39] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
```

**Comment by 4drian3d** [comment]
> @4drian3d
> 
> > Could you try the latest build? It should say a better debug message (you have to restart the config or the specific message option to re-generate it)
> 
> ```
> [22:18:27] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-1a1391a5-b155)...
> [22:18:27] [main/INFO]: Loading localizations...
> [22:18:27] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
> [22:18:27] [main/INFO]: Loading plugins...
> [22:18:28] [main/INFO]: Loaded plugin kickredirect 2.0.2 by 4drian3d
> [22:18:28] [main/INFO]: Loaded 1 plugins
> [22:18:28] [Velocity Async Event Executor - #0/INFO]: [KickRedirect] Starting plugin...
> [22:18:28] [Velocity Async Event Executor - #0/INFO]: [KickRedirect] Fully started plugin in 176ms
> [22:18:28] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
> [22:18:28] [main/INFO]: Done (1.33s)!
> [22:19:47] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283) has connected
> [22:19:47] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
> [22:20:12] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
> [22:20:13] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
> [22:20:38] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283): kicked from server survival: multiplayer.disconnect.kicked
> [22:20:38] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
> [22:20:38] [Velocity Async Event Executor - #2/INFO]: ----- INITIAL DEBUG ----- 
>  Player: Mad_Daniel
>  Server: NONE
>  Kick Reason: multiplayer.disconnect.kicked
>  Kicked in Server Connect: false
>  Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
>  Step: NOT_ALLOWED
> [22:20:38] [Velocity Async Event Executor - #2/INFO]: ----- FINAL DEBUG -----
>  Player: Mad_Daniel
>  Server: lobby
>  Kick Reason: multiplayer.disconnect.kicked
>  Kicked in Server Connect: false
>  Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
>  Step: NOT_ALLOWED
> [22:20:38] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
> [22:20:49] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
> [22:20:49] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
> [22:21:10] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283): kicked from server survival: test
> [22:21:10] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
> [22:21:10] [Velocity Async Event Executor - #4/INFO]: ----- INITIAL DEBUG ----- 
>  Player: Mad_Daniel
>  Server: NONE
>  Kick Reason: test
>  Kicked in Server Connect: false
>  Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
>  Step: NOT_ALLOWED
> [22:21:10] [Velocity Async Event Executor - #4/INFO]: ----- FINAL DEBUG -----
>  Player: Mad_Daniel
>  Server: lobby
>  Kick Reason: test
>  Kicked in Server Connect: false
>  Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
>  Step: NOT_ALLOWED
> [22:21:10] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
> [22:21:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has connected
> [22:21:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
> [22:21:39] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10283): kicked from server survival: kicked from server
> [22:21:39] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> survival has disconnected
> [22:21:39] [Velocity Async Event Executor - #6/INFO]: ----- INITIAL DEBUG ----- 
>  Player: Mad_Daniel
>  Server: NONE
>  Kick Reason: kicked from server
>  Kicked in Server Connect: false
>  Calculated result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
>  Step: NOT_ALLOWED
> [22:21:39] [Velocity Async Event Executor - #6/INFO]: ----- FINAL DEBUG -----
>  Player: Mad_Daniel
>  Server: lobby
>  Kick Reason: kicked from server
>  Kicked in Server Connect: false
>  Final Event Result: com.velocitypowered.api.event.player.KickedFromServerEvent$RedirectPlayer
>  Step: NOT_ALLOWED
> [22:21:39] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
> ```

Thank you very much, this last debug really gave me to understand what is going wrong.
https://github.com/PaperMC/Velocity/blob/1a1391a51916b111ceafe47bfbb144cf63cdc7ac/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L647 this specific line is the one I didn't expect to happen

**Comment by Pantera07** [comment]
Now it works fine.
